language: swift
osx_image: xcode11.0
xcode_workspace: moongae.xcworkspace
xcode_scheme: moongae
xcode_destination: platform=iOS Simulator, OS=11.4, name=iPhone 8
before_install:
- gem install cocoapods-acknowledgements
- gem install cocoapods
- pod update
