language: objective-c
osx_image: xcode11
xcode_workspace: moongae.xcworkspace
xcode_sdk: iphonesimulator
xcode_scheme: moongae
xcode_destination: platform=iOS Simulator, OS=11.3, name=iPhone 8
before_install:
- gem update cocoapods
- pod install --repo-update
script:
- travis_retry xctool -workspace moongae.xcworkspace -scheme "moongae" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO run-tests
- set -o pipefail
- travis_retry xcodebuild -workspace moongae.xcworkspace -scheme moongae -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c

